
// This file was auto-generated by ML.NET Model Builder. 

using SentimentModel_ConsoleApp1;
var sånn_ting = @"";
string path = "C:/Users/mas/Downloads/ml_new_model2.csv";

public class svartfil
{
    public int RENr { get; set; }

    public int Nr { get; set; }

    public string N { get; set; }

    public string Institusj { get; set; }

    public string CatNr { get; set; }

    public string Type { get; set; }

    public int AntId { get; set; }

    public int SumQ { get; set; }

    public string REKo { get; set; }

    public string RE_Navn { get; set; }

    public string Korr { get; set; }

    public string Forkastet { get; set; }

    public string Årsak { get; set; }

    public int X_2km { get; set; }

    public int Y_2km { get; set; }

    public int PrKI { get; set; }

    public string M { get; set; }

}

string[] lines = System.IO.File.ReadAllLines(path);
foreach (string line in lines)
{
    sånn_ting += line;
    Console.WriteLine(line);
    SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
    {
        Sånn_ting = line,
    };
}



// Make a single prediction on the sample data and print results
//var predictionResult = SentimentModel.Predict(sampleData);

//Console.WriteLine("Using model to make single prediction -- Comparing actual _0_1 with predicted _0_1 from sample data...\n\n");


//Console.WriteLine($"Sånn_ting: {@"Dyrøya, Berg. \ Beitebakke i berg."}");


//Console.WriteLine($"\n\nPredicted _0_1: {predictionResult.PredictedLabel}\n\n");
//Console.WriteLine("=============== End of process, hit any key to finish ===============");
//Console.ReadKey();

