# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile=release'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: dir Assessments.Frontend.Web
- script: dir Assessments.Frontend.Web\bin\Release
- script: dir Assessments.Frontend.Web\bin\Release\net5.0
- script: dir Assessments.Frontend.Web\bin

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Assessments.Frontend.Web\bin\Release\net5.0\'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ass-fe'
    publishLocation: 'Container'