# ASP.NET
# Build and test ASP.NET projects.

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration)'
