//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A×B - Median levetid × Ekspansjonshastighet.
        /// </summary>
        public static string A_B {
            get {
                return ResourceManager.GetString("A_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A×B hvor høyeste skår er....
        /// </summary>
        public static string A_B_highest_score {
            get {
                return ResourceManager.GetString("A_B_highest_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fraværende.
        /// </summary>
        public static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingen overføring ELLER begrenset overføring av eksisterende parasitt til eksisterende vert.
        /// </summary>
        public static string absent_OR_confined_known_host {
            get {
                return ResourceManager.GetString("absent_OR_confined_known_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fremmedartslista.
        /// </summary>
        public static string alien_species_list {
            get {
                return ResourceManager.GetString("alien_species_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to og.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forekomstareal i sterkt endra natur.
        /// </summary>
        public static string aoo_strongly_altered_nature {
            get {
                return ResourceManager.GetString("aoo_strongly_altered_nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forekomst i truede eller sjeldne naturtyper.
        /// </summary>
        public static string aoo_threatened_ecosystems {
            get {
                return ResourceManager.GetString("aoo_threatened_ecosystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Område.
        /// </summary>
        public static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mellom 160 og 499 m/år.
        /// </summary>
        public static string between_160_499_myear {
            get {
                return ResourceManager.GetString("between_160_499_myear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mellom 50 og 159 m/år.
        /// </summary>
        public static string between_50_159_myear {
            get {
                return ResourceManager.GetString("between_50_159_myear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mellom 60 og 649 år.
        /// </summary>
        public static string between_60_649_years {
            get {
                return ResourceManager.GetString("between_60_649_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mellom 10 og 59 år.
        /// </summary>
        public static string between_ten_59_years {
            get {
                return ResourceManager.GetString("between_ten_59_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien er endret fra 2018.
        /// </summary>
        public static string category_changed {
            get {
                return ResourceManager.GetString("category_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samme kategori som i 2018.
        /// </summary>
        public static string category_not_changed {
            get {
                return ResourceManager.GetString("category_not_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endring i risikokategori.
        /// </summary>
        public static string change_in_category {
            get {
                return ResourceManager.GetString("change_in_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merk alle.
        /// </summary>
        public static string choose_all {
            get {
                return ResourceManager.GetString("choose_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påvirket av klimaendringer.
        /// </summary>
        public static string climate_affected {
            get {
                return ResourceManager.GetString("climate_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betydning av klimaendringer for risiko.
        /// </summary>
        public static string climate_impact {
            get {
                return ResourceManager.GetString("climate_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke påvirket av klimaendringer.
        /// </summary>
        public static string climate_not_affected {
            get {
                return ResourceManager.GetString("climate_not_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fortrengning i begrenset omfang.
        /// </summary>
        public static string confined_displacement {
            get {
                return ResourceManager.GetString("confined_displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begrenset overføring til stedegen art.
        /// </summary>
        public static string confined_native_species {
            get {
                return ResourceManager.GetString("confined_native_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avgjørende kriterier for kategori.
        /// </summary>
        public static string decisive_criteria {
            get {
                return ResourceManager.GetString("decisive_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avgjørende kriterier.
        /// </summary>
        public static string decisive_criteria_short {
            get {
                return ResourceManager.GetString("decisive_criteria_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dørstokkarter.
        /// </summary>
        public static string doorknockers {
            get {
                return ResourceManager.GetString("doorknockers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ned mot.
        /// </summary>
        public static string down_to {
            get {
                return ResourceManager.GetString("down_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økologisk effekt.
        /// </summary>
        public static string ecological_effect {
            get {
                return ResourceManager.GetString("ecological_effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økologisk effekt påvirket av klimaendringer.
        /// </summary>
        public static string ecological_effect_climate_affected {
            get {
                return ResourceManager.GetString("ecological_effect_climate_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økologisk effekt ikke påvirket av klimaendringer.
        /// </summary>
        public static string ecological_effect_climate_not_affected {
            get {
                return ResourceManager.GetString("ecological_effect_climate_not_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påvirkning på arter og naturtyper i Norge.
        /// </summary>
        public static string ecological_effect_description {
            get {
                return ResourceManager.GetString("ecological_effect_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økologisk effekt (risikomatrisens y-akse).
        /// </summary>
        public static string ecological_effect_y_axis {
            get {
                return ResourceManager.GetString("ecological_effect_y_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naturtype.
        /// </summary>
        public static string ecosystem {
            get {
                return ResourceManager.GetString("ecosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturtyper.
        /// </summary>
        public static string ecosystems {
            get {
                return ResourceManager.GetString("ecosystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etableringsstatus i dag.
        /// </summary>
        public static string establishment_category {
            get {
                return ResourceManager.GetString("establishment_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vurdert for første gang.
        /// </summary>
        public static string first_time_assessed {
            get {
                return ResourceManager.GetString("first_time_assessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk variasjon i risiko.
        /// </summary>
        public static string geographic_var {
            get {
                return ResourceManager.GetString("geographic_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikoen er den samme innenfor artens potensielle forekomstareal.
        /// </summary>
        public static string geographic_var_equal {
            get {
                return ResourceManager.GetString("geographic_var_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikoen er ulik innenfor artens potensielle forekomstareal.
        /// </summary>
        public static string geographic_var_unequal {
            get {
                return ResourceManager.GetString("geographic_var_unequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to har.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikokategori.
        /// </summary>
        public static string impact_category {
            get {
                return ResourceManager.GetString("impact_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import til produksjons- eller innendørsareal.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduksjon til naturen.
        /// </summary>
        public static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasjonspotensial.
        /// </summary>
        public static string invasion_potential {
            get {
                return ResourceManager.GetString("invasion_potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasjonspotensial påvirket av klimaendringer.
        /// </summary>
        public static string invasion_potential_climate_affected {
            get {
                return ResourceManager.GetString("invasion_potential_climate_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasjonspotensial ikke påvirket av klimaendringer.
        /// </summary>
        public static string invasion_potential_climate_not_affected {
            get {
                return ResourceManager.GetString("invasion_potential_climate_not_affected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artens levedyktighet og evne til å ekspandere.
        /// </summary>
        public static string invasion_potential_description {
            get {
                return ResourceManager.GetString("invasion_potential_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasjonspotensial (risikomatrisens x-akse).
        /// </summary>
        public static string invasion_potential_x_axis {
            get {
                return ResourceManager.GetString("invasion_potential_x_axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidligere eller nåværende bruksart.
        /// </summary>
        public static string is_production_species {
            get {
                return ResourceManager.GetString("is_production_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fortrengning i storskala omfang.
        /// </summary>
        public static string large_scale_displacement {
            get {
                return ResourceManager.GetString("large_scale_displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storskala av eksisterende parasitt til eksisterende vert ELLER begrenset til ny vert.
        /// </summary>
        public static string large_scale_known_host_OR_confined_new_host {
            get {
                return ResourceManager.GetString("large_scale_known_host_OR_confined_new_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storskala av eksisterende parasitt til ny vert ELLER begrenset til ny truet vert.
        /// </summary>
        public static string large_scale_new_host_OR_confined_threathened_new_host {
            get {
                return ResourceManager.GetString("large_scale_new_host_OR_confined_threathened_new_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storskala av eksisterende parasitt til ny truet vert ELLER overføring av en dørstokkart-parasitt.
        /// </summary>
        public static string large_scale_new_threatened_host_OR_doorknocker_parasite {
            get {
                return ResourceManager.GetString("large_scale_new_threatened_host_OR_doorknocker_parasite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storskala overføring  til stedegen art ELLER begrenset til truet art eller nøkkelart.
        /// </summary>
        public static string large_scale_non_threatened_OR_confined_threatened {
            get {
                return ResourceManager.GetString("large_scale_non_threatened_OR_confined_threatened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storskala overføring til truet art eller nøkkelart.
        /// </summary>
        public static string large_scale_threatened {
            get {
                return ResourceManager.GetString("large_scale_threatened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mindre enn 50 m/år.
        /// </summary>
        public static string less_than_50_myear {
            get {
                return ResourceManager.GetString("less_than_50_myear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mindre enn 5%.
        /// </summary>
        public static string less_than_five_percent {
            get {
                return ResourceManager.GetString("less_than_five_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mindre enn 10 år.
        /// </summary>
        public static string less_than_ten_years {
            get {
                return ResourceManager.GetString("less_than_ten_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livsmiljø.
        /// </summary>
        public static string lifestyle {
            get {
                return ResourceManager.GetString("lifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 5%.
        /// </summary>
        public static string min_five_percent {
            get {
                return ResourceManager.GetString("min_five_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 2%.
        /// </summary>
        public static string min_two_percent {
            get {
                return ResourceManager.GetString("min_two_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 20%.
        /// </summary>
        public static string minimum_20_percent {
            get {
                return ResourceManager.GetString("minimum_20_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 500 m/år.
        /// </summary>
        public static string minimum_500_myear {
            get {
                return ResourceManager.GetString("minimum_500_myear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 650 år.
        /// </summary>
        public static string minimum_650_years {
            get {
                return ResourceManager.GetString("minimum_650_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 10%.
        /// </summary>
        public static string minimum_ten_percent {
            get {
                return ResourceManager.GetString("minimum_ten_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderat styrke og storskala omfang.
        /// </summary>
        public static string moderate_large_scale {
            get {
                return ResourceManager.GetString("moderate_large_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderat styrke og storskala omfang ELLER fortrengning.
        /// </summary>
        public static string moderate_large_scale_or_displacement {
            get {
                return ResourceManager.GetString("moderate_large_scale_or_displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingen overføring.
        /// </summary>
        public static string no_transfer {
            get {
                return ResourceManager.GetString("no_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Øvrige kriterier.
        /// </summary>
        public static string non_decisive_criteria {
            get {
                return ResourceManager.GetString("non_decisive_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke-risikovurderte arter.
        /// </summary>
        public static string not_assessed_species {
            get {
                return ResourceManager.GetString("not_assessed_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke bruksart.
        /// </summary>
        public static string not_production_species {
            get {
                return ResourceManager.GetString("not_production_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to på.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over 0%.
        /// </summary>
        public static string over_zero_percent {
            get {
                return ResourceManager.GetString("over_zero_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spredningsmåter.
        /// </summary>
        public static string pathways {
            get {
                return ResourceManager.GetString("pathways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruksart.
        /// </summary>
        public static string production_species {
            get {
                return ResourceManager.GetString("production_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionalt fremmede arter.
        /// </summary>
        public static string regionally_alien {
            get {
                return ResourceManager.GetString("regionally_alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekskluder regionalt fremmede arter.
        /// </summary>
        public static string regionally_alien_exclude {
            get {
                return ResourceManager.GetString("regionally_alien_exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kun vis regionalt fremmede arter.
        /// </summary>
        public static string regionally_alien_only {
            get {
                return ResourceManager.GetString("regionally_alien_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionvis utbredelse.
        /// </summary>
        public static string regionally_distribution {
            get {
                return ResourceManager.GetString("regionally_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regioner med kjent, antatt eller forventet forekomst.
        /// </summary>
        public static string regions_expected_occurrence {
            get {
                return ResourceManager.GetString("regions_expected_occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regioner og havområder.
        /// </summary>
        public static string regions_oceans {
            get {
                return ResourceManager.GetString("regions_oceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skår.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artsgrupper.
        /// </summary>
        public static string species_groups {
            get {
                return ResourceManager.GetString("species_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spredning i naturen.
        /// </summary>
        public static string spread {
            get {
                return ResourceManager.GetString("spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksonomi.
        /// </summary>
        public static string taxonomy {
            get {
                return ResourceManager.GetString("taxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til artssiden.
        /// </summary>
        public static string to_species_page {
            get {
                return ResourceManager.GetString("to_species_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opp mot.
        /// </summary>
        public static string up_to {
            get {
                return ResourceManager.GetString("up_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vannregioner.
        /// </summary>
        public static string water_regions {
            get {
                return ResourceManager.GetString("water_regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svak styrke og begrenset omfang.
        /// </summary>
        public static string weak_confined {
            get {
                return ResourceManager.GetString("weak_confined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svak styrke og storskala omfang ELLER moderat styrke og begrenset omfang.
        /// </summary>
        public static string weak_large_scale_or_moderate_confined {
            get {
                return ResourceManager.GetString("weak_large_scale_or_moderate_confined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svak styrke ELLER moderat styrke og begrenset omfang.
        /// </summary>
        public static string weak_or_moderate_confined {
            get {
                return ResourceManager.GetString("weak_or_moderate_confined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to som er.
        /// </summary>
        public static string which_is {
            get {
                return ResourceManager.GetString("which_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med usikkerhet.
        /// </summary>
        public static string with_uncertainty {
            get {
                return ResourceManager.GetString("with_uncertainty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string zero_percent {
            get {
                return ResourceManager.GetString("zero_percent", resourceCulture);
            }
        }
    }
}
