//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023MatrixAxisScoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023MatrixAxisScoreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023MatrixA" +
                            "xisScoreResource", typeof(AlienSpeciesAssessment2023MatrixAxisScoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stort.
        /// </summary>
        public static string great {
            get {
                return ResourceManager.GetString("great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stor.
        /// </summary>
        public static string large {
            get {
                return ResourceManager.GetString("large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begrensa.
        /// </summary>
        public static string limited {
            get {
                return ResourceManager.GetString("limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liten.
        /// </summary>
        public static string little {
            get {
                return ResourceManager.GetString("little", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middels.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderat.
        /// </summary>
        public static string moderate {
            get {
                return ResourceManager.GetString("moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen kjent.
        /// </summary>
        public static string no_known {
            get {
                return ResourceManager.GetString("no_known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite.
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukjent.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
