//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023MajorTypeGroupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023MajorTypeGroupResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023MajorTy" +
                            "peGroupResource", typeof(AlienSpeciesAssessment2023MajorTypeGroupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skog.
        /// </summary>
        public static string forest_threatned {
            get {
                return ResourceManager.GetString("forest_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innsjøbunnsystemer.
        /// </summary>
        public static string freshwater_bottom_systems {
            get {
                return ResourceManager.GetString("freshwater_bottom_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferskvann.
        /// </summary>
        public static string freshwater_threatned {
            get {
                return ResourceManager.GetString("freshwater_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landform.
        /// </summary>
        public static string landform_threatned {
            get {
                return ResourceManager.GetString("landform_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limniske vannmasser.
        /// </summary>
        public static string limnic_waterbody_systems {
            get {
                return ResourceManager.GetString("limnic_waterbody_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltvannsbunnsystemer.
        /// </summary>
        public static string marine_seabed_systems {
            get {
                return ResourceManager.GetString("marine_seabed_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marint gruntvann, Svalbard.
        /// </summary>
        public static string marine_water_Svalbard_threatned {
            get {
                return ResourceManager.GetString("marine_water_Svalbard_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marint gruntvann.
        /// </summary>
        public static string marine_water_threatned {
            get {
                return ResourceManager.GetString("marine_water_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine vannmasser.
        /// </summary>
        public static string marine_waterbody_systems {
            get {
                return ResourceManager.GetString("marine_waterbody_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjell og berg.
        /// </summary>
        public static string mountains_threatned {
            get {
                return ResourceManager.GetString("mountains_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elvebunnsystemer.
        /// </summary>
        public static string river_bottom_systems {
            get {
                return ResourceManager.GetString("river_bottom_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-naturlig.
        /// </summary>
        public static string semi_natural_threatned {
            get {
                return ResourceManager.GetString("semi_natural_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snø- og issystemer.
        /// </summary>
        public static string snow_ice_systems {
            get {
                return ResourceManager.GetString("snow_ice_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svalbard.
        /// </summary>
        public static string Svalbard_threatned {
            get {
                return ResourceManager.GetString("Svalbard_threatned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastmarkssystemer.
        /// </summary>
        public static string terrestrial_systems {
            get {
                return ResourceManager.GetString("terrestrial_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukjent.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våtmarkssystemer.
        /// </summary>
        public static string wetland_systems {
            get {
                return ResourceManager.GetString("wetland_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våtmark.
        /// </summary>
        public static string wetlands_threatned {
            get {
                return ResourceManager.GetString("wetlands_threatned", resourceCulture);
            }
        }
    }
}
