//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023SpeciesStatusResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023SpeciesStatusResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Species" +
                            "StatusResource", typeof(AlienSpeciesAssessment2023SpeciesStatusResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observert i norsk natur.
        /// </summary>
        public static string documented_Norwegian_nature {
            get {
                return ResourceManager.GetString("documented_Norwegian_nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er dokumentert fra norsk natur.
        /// </summary>
        public static string documented_Norwegian_nature_description {
            get {
                return ResourceManager.GetString("documented_Norwegian_nature_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablert.
        /// </summary>
        public static string established {
            get {
                return ResourceManager.GetString("established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er etablert.
        /// </summary>
        public static string established_description {
            get {
                return ResourceManager.GetString("established_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innendørs.
        /// </summary>
        public static string indoors {
            get {
                return ResourceManager.GetString("indoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forekommer innendørs eller i lukkede installasjoner.
        /// </summary>
        public static string indoors_description {
            get {
                return ResourceManager.GetString("indoors_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke i Norge.
        /// </summary>
        public static string not_in_Norway {
            get {
                return ResourceManager.GetString("not_in_Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ikke forekommer i Norge.
        /// </summary>
        public static string not_in_Norway_description {
            get {
                return ResourceManager.GetString("not_in_Norway_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke angitt.
        /// </summary>
        public static string not_indicated {
            get {
                return ResourceManager.GetString("not_indicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utendørs i eget produksjonsareal.
        /// </summary>
        public static string outdoors_production_area {
            get {
                return ResourceManager.GetString("outdoors_production_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forekommer utendørs i eget produksjonsareal.
        /// </summary>
        public static string outdoors_production_area_description {
            get {
                return ResourceManager.GetString("outdoors_production_area_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er selvstendig reproduserende.
        /// </summary>
        public static string reproduces_unaidedly_description {
            get {
                return ResourceManager.GetString("reproduces_unaidedly_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlever vinteren utendørs.
        /// </summary>
        public static string survive_winter_outdoors {
            get {
                return ResourceManager.GetString("survive_winter_outdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kan overleve vinteren utendørs og uten hjelp.
        /// </summary>
        public static string survive_winter_outdoors_description {
            get {
                return ResourceManager.GetString("survive_winter_outdoors_description", resourceCulture);
            }
        }
    }
}
