//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023AreaOfOccupancyInStronglyAlteredEcosystemsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023AreaOfOccupancyInStronglyAlteredEcosystemsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023AreaOfO" +
                            "ccupancyInStronglyAlteredEcosystemsResource", typeof(AlienSpeciesAssessment2023AreaOfOccupancyInStronglyAlteredEcosystemsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra og med 5 % til 25 %.
        /// </summary>
        public static string from_five_to_twentyfive {
            get {
                return ResourceManager.GetString("from_five_to_twentyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra 75 % til og med 95 %.
        /// </summary>
        public static string From_seventyfive_to_ninetyfive {
            get {
                return ResourceManager.GetString("From_seventyfive_to_ninetyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra og med 25 % til og med 75 %.
        /// </summary>
        public static string from_twentyfive_to_seventyfive {
            get {
                return ResourceManager.GetString("from_twentyfive_to_seventyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under 5 %.
        /// </summary>
        public static string less_than_five {
            get {
                return ResourceManager.GetString("less_than_five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over 95 %.
        /// </summary>
        public static string over_ninetyfive {
            get {
                return ResourceManager.GetString("over_ninetyfive", resourceCulture);
            }
        }
    }
}
