//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023RegionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023RegionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023RegionR" +
                            "esource", typeof(AlienSpeciesAssessment2023RegionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barentshavet nord og Polhavet.
        /// </summary>
        public static string barents_north_polar {
            get {
                return ResourceManager.GetString("barents_north_polar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barentshavet sør.
        /// </summary>
        public static string barents_south {
            get {
                return ResourceManager.GetString("barents_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grønlandshavet.
        /// </summary>
        public static string greenland_sea {
            get {
                return ResourceManager.GetString("greenland_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordsjøen og Skagerrak.
        /// </summary>
        public static string north_sea {
            get {
                return ResourceManager.GetString("north_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norskehavet.
        /// </summary>
        public static string norwegian_ocean {
            get {
                return ResourceManager.GetString("norwegian_ocean", resourceCulture);
            }
        }
    }
}
