//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023CriteriaLetterResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023CriteriaLetterResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Criteri" +
                            "aLetterResource", typeof(AlienSpeciesAssessment2023CriteriaLetterResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median levetid.
        /// </summary>
        public static string A_median_lifetime {
            get {
                return ResourceManager.GetString("A_median_lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspansjonshastighet.
        /// </summary>
        public static string B_expansion_speed {
            get {
                return ResourceManager.GetString("B_expansion_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolonisering av naturtype.
        /// </summary>
        public static string C_colonized_area {
            get {
                return ResourceManager.GetString("C_colonized_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effekter på truede arter eller nøkkelarter.
        /// </summary>
        public static string D_effects_threatened_species {
            get {
                return ResourceManager.GetString("D_effects_threatened_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effekter på øvrige stedegne arter.
        /// </summary>
        public static string E_effects_other_species {
            get {
                return ResourceManager.GetString("E_effects_other_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effekter på truede eller sjeldne naturtyper.
        /// </summary>
        public static string F_effects_threatened_ecosystems {
            get {
                return ResourceManager.GetString("F_effects_threatened_ecosystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effekter på øvrige naturtyper.
        /// </summary>
        public static string G_effects_other_ecosystems {
            get {
                return ResourceManager.GetString("G_effects_other_ecosystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overføring av genetisk materiale.
        /// </summary>
        public static string H_transfer_genetic_material {
            get {
                return ResourceManager.GetString("H_transfer_genetic_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overføring av parasitter eller patogener.
        /// </summary>
        public static string I_transfer_parasites {
            get {
                return ResourceManager.GetString("I_transfer_parasites", resourceCulture);
            }
        }
    }
}
