//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023SpeciesGroupsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023SpeciesGroupsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Species" +
                            "GroupsResource", typeof(AlienSpeciesAssessment2023SpeciesGroupsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisker.
        /// </summary>
        public static string actinopterygii {
            get {
                return ResourceManager.GetString("actinopterygii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amfibier.
        /// </summary>
        public static string amphibia {
            get {
                return ResourceManager.GetString("amphibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leddormer.
        /// </summary>
        public static string annelida {
            get {
                return ResourceManager.GetString("annelida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edderkoppdyr.
        /// </summary>
        public static string arachnida {
            get {
                return ResourceManager.GetString("arachnida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kappedyr.
        /// </summary>
        public static string ascidiacea_tunicata {
            get {
                return ResourceManager.GetString("ascidiacea_tunicata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fugler.
        /// </summary>
        public static string aves {
            get {
                return ResourceManager.GetString("aves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakterier.
        /// </summary>
        public static string bacteria {
            get {
                return ResourceManager.GetString("bacteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bladfotinger.
        /// </summary>
        public static string branchiopoda {
            get {
                return ResourceManager.GetString("branchiopoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moser.
        /// </summary>
        public static string bryophyta_marchantiophyta {
            get {
                return ResourceManager.GetString("bryophyta_marchantiophyta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grønnalger.
        /// </summary>
        public static string chlorophyta {
            get {
                return ResourceManager.GetString("chlorophyta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesledyr.
        /// </summary>
        public static string cnidaria {
            get {
                return ResourceManager.GetString("cnidaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biller.
        /// </summary>
        public static string coleoptera {
            get {
                return ResourceManager.GetString("coleoptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppekreps.
        /// </summary>
        public static string copepoda {
            get {
                return ResourceManager.GetString("copepoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krepsdyr.
        /// </summary>
        public static string crustacea {
            get {
                return ResourceManager.GetString("crustacea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kammaneter.
        /// </summary>
        public static string ctenophora {
            get {
                return ResourceManager.GetString("ctenophora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovinger.
        /// </summary>
        public static string diptera {
            get {
                return ResourceManager.GetString("diptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pigghuder.
        /// </summary>
        public static string echinodermata {
            get {
                return ResourceManager.GetString("echinodermata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosdyr og begerormer.
        /// </summary>
        public static string ectoprocta_entoprocta {
            get {
                return ResourceManager.GetString("ectoprocta_entoprocta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sopper.
        /// </summary>
        public static string fungi {
            get {
                return ResourceManager.GetString("fungi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebbmunner.
        /// </summary>
        public static string hemiptera {
            get {
                return ResourceManager.GetString("hemiptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vepser.
        /// </summary>
        public static string hymenoptera {
            get {
                return ResourceManager.GetString("hymenoptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insekter.
        /// </summary>
        public static string insecta {
            get {
                return ResourceManager.GetString("insecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sommerfugler.
        /// </summary>
        public static string lepidoptera {
            get {
                return ResourceManager.GetString("lepidoptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planter.
        /// </summary>
        public static string magnoliophyta_pinophyta_pteridophyta {
            get {
                return ResourceManager.GetString("magnoliophyta_pinophyta_pteridophyta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storkrepser.
        /// </summary>
        public static string malacostraca {
            get {
                return ResourceManager.GetString("malacostraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattedyr.
        /// </summary>
        public static string mammalia {
            get {
                return ResourceManager.GetString("mammalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bløtdyr.
        /// </summary>
        public static string mollusca {
            get {
                return ResourceManager.GetString("mollusca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangefotinger.
        /// </summary>
        public static string myriapoda_chilopoda_diplopoda_dauropoda_symphyla {
            get {
                return ResourceManager.GetString("myriapoda_chilopoda_diplopoda_dauropoda_symphyla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rundormer.
        /// </summary>
        public static string nematoda {
            get {
                return ResourceManager.GetString("nematoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggsporesopper.
        /// </summary>
        public static string oomycota {
            get {
                return ResourceManager.GetString("oomycota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunalger.
        /// </summary>
        public static string phaeophyceae {
            get {
                return ResourceManager.GetString("phaeophyceae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lus.
        /// </summary>
        public static string phthiraptera {
            get {
                return ResourceManager.GetString("phthiraptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatormer.
        /// </summary>
        public static string platyhelminthes {
            get {
                return ResourceManager.GetString("platyhelminthes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svamper.
        /// </summary>
        public static string porifera {
            get {
                return ResourceManager.GetString("porifera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Støvlus.
        /// </summary>
        public static string psocoptera {
            get {
                return ResourceManager.GetString("psocoptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havedderkopper.
        /// </summary>
        public static string pycnogonida {
            get {
                return ResourceManager.GetString("pycnogonida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptiler.
        /// </summary>
        public static string reptilia {
            get {
                return ResourceManager.GetString("reptilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rødalger.
        /// </summary>
        public static string rhodophyta {
            get {
                return ResourceManager.GetString("rhodophyta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alger.
        /// </summary>
        public static string rhodophyta_chlorophyta_phaeophyceae {
            get {
                return ResourceManager.GetString("rhodophyta_chlorophyta_phaeophyceae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjuldyr.
        /// </summary>
        public static string rotifera {
            get {
                return ResourceManager.GetString("rotifera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankefotinger.
        /// </summary>
        public static string thecostraca {
            get {
                return ResourceManager.GetString("thecostraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips.
        /// </summary>
        public static string thysanoptera {
            get {
                return ResourceManager.GetString("thysanoptera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Børstehaler.
        /// </summary>
        public static string zygentoma {
            get {
                return ResourceManager.GetString("zygentoma", resourceCulture);
            }
        }
    }
}
