//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023IntroductionPathwayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023IntroductionPathwayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Introdu" +
                            "ctionPathwayResource", typeof(AlienSpeciesAssessment2023IntroductionPathwayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opphørt, men kan inntreffe igjen.
        /// </summary>
        public static string ceased {
            get {
                return ResourceManager.GetString("ceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forurensning av vare.
        /// </summary>
        public static string contaminant {
            get {
                return ResourceManager.GetString("contaminant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som forurensning av vare.
        /// </summary>
        public static string contaminant_description {
            get {
                return ResourceManager.GetString("contaminant_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korridor.
        /// </summary>
        public static string corridor {
            get {
                return ResourceManager.GetString("corridor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via menneskeskapt korridor.
        /// </summary>
        public static string corridor_description {
            get {
                return ResourceManager.GetString("corridor_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rømning/forvilling.
        /// </summary>
        public static string escape {
            get {
                return ResourceManager.GetString("escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kun i fremtiden.
        /// </summary>
        public static string future {
            get {
                return ResourceManager.GetString("future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kun historisk.
        /// </summary>
        public static string historic {
            get {
                return ResourceManager.GetString("historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direkte import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilsiktet utsetting.
        /// </summary>
        public static string intentionally_released {
            get {
                return ResourceManager.GetString("intentionally_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egenspredning.
        /// </summary>
        public static string natural_dispersal {
            get {
                return ResourceManager.GetString("natural_dispersal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallrike ganger pr. år.
        /// </summary>
        public static string numerous_yearly {
            get {
                return ResourceManager.GetString("numerous_yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågående.
        /// </summary>
        public static string ongoing {
            get {
                return ResourceManager.GetString("ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjeldnere enn hvert 10. år.
        /// </summary>
        public static string rarer_than_ten_years {
            get {
                return ResourceManager.GetString("rarer_than_ten_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flere ganger pr. 10. år.
        /// </summary>
        public static string several_per_ten_years {
            get {
                return ResourceManager.GetString("several_per_ten_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindpassasjer med transport.
        /// </summary>
        public static string stowaway {
            get {
                return ResourceManager.GetString("stowaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som blindpassasjer.
        /// </summary>
        public static string stowaway_description {
            get {
                return ResourceManager.GetString("stowaway_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca. årlig.
        /// </summary>
        public static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
    }
}
