//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023ScientificNameRankResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023ScientificNameRankResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Scienti" +
                            "ficNameRankResource", typeof(AlienSpeciesAssessment2023ScientificNameRankResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkludert i vurdering på annet taksonomisk nivå.
        /// </summary>
        public static string assessed_at_another_rank {
            get {
                return ResourceManager.GetString("assessed_at_another_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string form {
            get {
                return ResourceManager.GetString("form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke inkludert i vurdering på annet taksonomisk nivå.
        /// </summary>
        public static string not_assessed_at_another_rank {
            get {
                return ResourceManager.GetString("not_assessed_at_another_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string species {
            get {
                return ResourceManager.GetString("species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underart.
        /// </summary>
        public static string subspecies {
            get {
                return ResourceManager.GetString("subspecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksonomisk nivå.
        /// </summary>
        public static string taxonomic_rank {
            get {
                return ResourceManager.GetString("taxonomic_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varietet.
        /// </summary>
        public static string variety {
            get {
                return ResourceManager.GetString("variety", resourceCulture);
            }
        }
    }
}
