//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023AlienSpeciesCategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023AlienSpeciesCategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023AlienSp" +
                            "eciesCategoryResource", typeof(AlienSpeciesAssessment2023AlienSpeciesCategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selvstendig reproduserende.
        /// </summary>
        public static string alien_species {
            get {
                return ResourceManager.GetString("alien_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreligger separate vurderinger av infraspesifikke taksa.
        /// </summary>
        public static string all_subtaxa_assessed_separately {
            get {
                return ResourceManager.GetString("all_subtaxa_assessed_separately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dørstokkart.
        /// </summary>
        public static string doorknocker {
            get {
                return ResourceManager.GetString("doorknocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økologisk effekt uten selvstendig reproduksjon innen 50 år.
        /// </summary>
        public static string effect_without_reproduction {
            get {
                return ResourceManager.GetString("effect_without_reproduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablert per år 1800.
        /// </summary>
        public static string established_at_1800 {
            get {
                return ResourceManager.GetString("established_at_1800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vurderes på et annet taksonomisk nivå.
        /// </summary>
        public static string evaluated_at_another_level {
            get {
                return ResourceManager.GetString("evaluated_at_another_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horisontskannet.
        /// </summary>
        public static string horizon_scanned_but_no_risk_assessment {
            get {
                return ResourceManager.GetString("horizon_scanned_but_no_risk_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utenfor avgrensningen.
        /// </summary>
        public static string hybrid_without_own_risk_assessment {
            get {
                return ResourceManager.GetString("hybrid_without_own_risk_assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidligere feilbestemt.
        /// </summary>
        public static string misidentified {
            get {
                return ResourceManager.GetString("misidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke fremmed.
        /// </summary>
        public static string not_alien_species {
            get {
                return ResourceManager.GetString("not_alien_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionalt fremmed.
        /// </summary>
        public static string regionally_alien {
            get {
                return ResourceManager.GetString("regionally_alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionalt fremmed og etablert per år 1800.
        /// </summary>
        public static string regionally_alien_established_at_1800 {
            get {
                return ResourceManager.GetString("regionally_alien_established_at_1800", resourceCulture);
            }
        }
    }
}
