//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Shared.Resources.Enums.AlienSpecies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlienSpeciesAssessment2023EnvironmentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlienSpeciesAssessment2023EnvironmentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessments.Shared.Resources.Enums.AlienSpecies.AlienSpeciesAssessment2023Environ" +
                            "mentResource", typeof(AlienSpeciesAssessment2023EnvironmentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limnisk, marint og terrestrisk.
        /// </summary>
        public static string all_lifestyles {
            get {
                return ResourceManager.GetString("all_lifestyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limnisk.
        /// </summary>
        public static string limnic {
            get {
                return ResourceManager.GetString("limnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limnisk og marint.
        /// </summary>
        public static string limnic_marine {
            get {
                return ResourceManager.GetString("limnic_marine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limnisk og terrestrisk.
        /// </summary>
        public static string limnic_terrestrial {
            get {
                return ResourceManager.GetString("limnic_terrestrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marint.
        /// </summary>
        public static string marine {
            get {
                return ResourceManager.GetString("marine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marint og terrestrisk.
        /// </summary>
        public static string marine_terrestrial {
            get {
                return ResourceManager.GetString("marine_terrestrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terrestrisk.
        /// </summary>
        public static string terrestric {
            get {
                return ResourceManager.GetString("terrestric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukjent livsmiljø.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
