
name: .NET Core

on:
  push:
    branches: 
      - 'main'
      - 'master'
  pull_request:
    types: [closed]
    branches: 
      - 'main'
      - 'master'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build and push Docker image api
      uses: docker/build-push-action@v1
      if: github.event.pull_request.merged == 'true' && ${{ github.actor != 'dependabot[bot]' }}
      with:
        username: ${{ secrets.ORG_DOCKER_USER }}
        password: ${{ secrets.ORG_DOCKER_PASS }}
        dockerfile: Assessments.Frontend.Web/Dockerfile
        repository: artsdatabanken/assessments-fe
        tags: latest
