
name: Test aka staging
#Builds and publishes PRs to "stable" test

on:
  pull_request:
    types: [closed]
    branches: 
      - 'test'
   
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build and push Docker image api
      uses: docker/build-push-action@v1
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        username: ${{ secrets.ORG_DOCKER_USER }}
        password: ${{ secrets.ORG_DOCKER_PASS }}
        dockerfile: Assessments.Frontend.Web/Dockerfile
        repository: artsdatabanken/assessments-fe
        tags: test
    - name: Post to slack
      if: ${{ github.actor != 'dependabot[bot]' }}
      run: .github/workflows/slack.sh ${{ secrets.POST_SLACK }}
